#!/bin/bash
if [[ $USER != root ]]; then
    sudo podman build --squash-all --cap-add SYS_ADMIN -t matyasosg/centos-8-stream:latest .  && \
    sudo podman save matyasosg/centos-8-stream:latest | podman load
else
    podman build --squash-all --cap-add SYS_ADMIN matyasosg/centos-8-stream:latest .
fi
